[book]
authors = ["Michael-F-Bryan"]
language = "en"
src = "."
title = "Wasmer Pack User Guide"

[output.html]
default-theme = "rust"
edit-url-template = "https://github.com/wasmerio/wasmer-pack/edit/master/{path}"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
optional = true # Only run the linkchecker when mdbook-linkcheck is installed

[output.literate]
optional = true
include = ["tutorial/*"]
